export const ReadMethod = {
  CLAIM_COOLDOWN: 'CLAIM_COOLDOWN',
  ENTRY_FEE: 'ENTRY_FEE',
  MAX_DIFFICULTY: 'MAX_DIFFICULTY',
  MAX_ENTRY_FEE: 'MAX_ENTRY_FEE',
  MAX_GAME_TYPE: 'MAX_GAME_TYPE',
  MIN_ENTRY_FEE: 'MIN_ENTRY_FEE',
  CAN_CLAIM_PRIZE: 'canClaimPrize',
  CHECK_ACCESS: 'checkAccess',
  CREATOR_EARNINGS: 'creatorEarnings',
  ENTRY_FEE_CURRENT: 'entryFee',
  GET_ARCADE_STATS: 'getArcadeStats',
  GET_CURRENT_SEASON: 'getCurrentSeason',
  GET_LEADERBOARD: 'getLeaderboard',
  GET_MULTIPLIER: 'getMultiplier',
  GET_PLAYER_STATS: 'getPlayerStats',
  GET_PRIZE_POOL: 'getPrizePool',
  GET_TIME_UNTIL_NEXT_CLAIM: 'getTimeUntilNextClaim',
  GET_TOP_PLAYER: 'getTopPlayer',
  LAST_CLAIM_TIME: 'lastClaimTime',
  OWNER: 'owner',
  PRIZE_POOL: 'prizePool',
  SEASON_NUMBER: 'seasonNumber',
  SEASON_START_TIME: 'seasonStartTime',
  TOTAL_GAMES_PLAYED: 'totalGamesPlayed',
  TOTAL_PLAYERS: 'totalPlayers',
  USDM_TOKEN: 'usdmToken',
} as const;
